/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.gianHangController;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author PC
 */
public class gianHangView extends javax.swing.JFrame {
    gianHangController Controller = new gianHangController();
    private static int tien=0;

    public int getTien() {
        return tien;
    }

    public void setTien(int tien) {
        this.tien = tien;
    }
    
    /**
     * Creates new form gianHangView
     */
    private static gianHangView instance=null;
    public static gianHangView getInstance(){
        if(instance==null)
            instance=new gianHangView();
        return instance;
    }
    public gianHangView() {
        initComponents();
        loadTable();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GHtable = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txfTimKiem = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ViTrijLabel = new javax.swing.JLabel();
        KichThuocjLabel = new javax.swing.JLabel();
        cbViTri = new javax.swing.JComboBox<>();
        cbKichThuoc = new javax.swing.JComboBox<>();
        txfViTri = new javax.swing.JTextField();
        txfKichThuoc = new javax.swing.JTextField();
        GiajLabel = new javax.swing.JLabel();
        txfGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfTinhTrang = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Gian Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        GHtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã gian hàng", "Vị trí", "Kích thước", "Giá", "Tình trạng"
            }
        ));
        GHtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GHtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GHtable);

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-20.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(204, 204, 0));

        ViTrijLabel.setForeground(new java.awt.Color(204, 204, 0));
        ViTrijLabel.setText("Vị trí");

        KichThuocjLabel.setForeground(new java.awt.Color(204, 204, 0));
        KichThuocjLabel.setText("Kích thuớc");

        cbViTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bình thường", "đẹp" }));
        cbViTri.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbViTriPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViTriActionPerformed(evt);
            }
        });

        cbKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3mx3m", "3mx4m" }));
        cbKichThuoc.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbKichThuocPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txfViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfViTriActionPerformed(evt);
            }
        });

        GiajLabel.setForeground(new java.awt.Color(204, 204, 0));
        GiajLabel.setText("Giá");

        txfGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfGiaMouseClicked(evt);
            }
        });
        txfGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGiaActionPerformed(evt);
            }
        });
        txfGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfGiaKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Tình trạng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViTrijLabel)
                    .addComponent(KichThuocjLabel)
                    .addComponent(GiajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbViTri, 0, 194, Short.MAX_VALUE)
                    .addComponent(txfViTri)
                    .addComponent(cbKichThuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfKichThuoc)
                    .addComponent(txfGia)
                    .addComponent(txfTinhTrang))
                .addGap(38, 38, 38))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {KichThuocjLabel, ViTrijLabel});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViTrijLabel)
                    .addComponent(cbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txfViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KichThuocjLabel)
                    .addComponent(cbKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txfKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GiajLabel)
                            .addComponent(txfGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txfTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {KichThuocjLabel, ViTrijLabel});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txfKichThuoc, txfViTri});

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-left-20.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-plus-20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 255, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-minus-20.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-update-left-rotation-20.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addGap(160, 160, 160)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat))
                .addGap(292, 292, 292))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViTriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbViTriActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        if(evt.getSource().equals(btnThoat)){
            btnTrangChu();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbViTriPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbViTriPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp=(String) cbViTri.getSelectedItem();
        txfViTri.setText(tmp);
        
    }//GEN-LAST:event_cbViTriPopupMenuWillBecomeInvisible

    private void cbKichThuocPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbKichThuocPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp=(String) cbKichThuoc.getSelectedItem();
        txfKichThuoc.setText(tmp);
       
    }//GEN-LAST:event_cbKichThuocPopupMenuWillBecomeInvisible

    private void GHtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GHtableMouseClicked
        // TODO add your handling code here:
        int i=GHtable.getSelectedRow();
        TableModel model= GHtable.getModel();
        txfViTri.setText(model.getValueAt(i, 1).toString());
        txfKichThuoc.setText(model.getValueAt(i, 2).toString());
        txfGia.setText(model.getValueAt(i, 3).toString());
        txfTinhTrang.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_GHtableMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Controller.timGianHang(GHtable, txfTimKiem.getText());
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String vitri=txfViTri.getText();
        String kichthuoc=txfKichThuoc.getText();
        String gia=txfGia.getText();
        String tinhtrang=txfTinhTrang.getText();
        if(txfViTri.getText().equals("")||txfKichThuoc.getText().equals("")||txfGia.getText().equals("")||txfTinhTrang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
        else
        {
            if(Controller.themGH(vitri, kichthuoc, gia, tinhtrang)){
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                loadTable();
                tayText();
            }
            else{
                JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Thêm nhân viên thất bại !","Thông báo", JOptionPane.OK_OPTION);
            }                                                        
        }
//                    }
//            }  
    }//GEN-LAST:event_btnThemActionPerformed

    private void txfGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfGiaMouseClicked
        // TODO add your handling code here:
        if(txfViTri.getText().equals("đẹp")&&txfKichThuoc.getText().equals("3mx3m"))
        {
            tien=700;
        }
        else if(txfViTri.getText().equals("đẹp")&&txfKichThuoc.getText().equals("3mx4m"))
            tien=800;
        if(txfViTri.getText().equals("bình thường")&&txfKichThuoc.getText().equals("3mx4m"))
        {
            tien=600;
        }
        else if(txfViTri.getText().equals("bình thường")&&txfKichThuoc.getText().equals("3mx3m"))
            tien=500;
        String tien1=String.valueOf(tien);
        txfGia.setText(tien1);
    }//GEN-LAST:event_txfGiaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex =GHtable.getSelectedRow();
        if(selectedIndex==-1)
            JOptionPane.showMessageDialog(rootPane, 
                    "Chọn gian hàng cần xóa");
        int data=GHtable.getSelectedRow();
        String magh=GHtable.getModel().getValueAt(data, 0).toString();
            int result=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không");
            if(result==0){
                if(Controller.xoaGH(magh)){
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    loadTable();
                    tayText();
                }
                else{
                    JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Xóa thất bại !","Thông báo", JOptionPane.OK_OPTION);
                     tayText();
                }
            
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        String vitri=txfViTri.getText();
        String kichthuoc=txfKichThuoc.getText();
        String gia=txfGia.getText();
        String tinhtrang=txfTinhTrang.getText();
        
        int position =GHtable.getSelectedRow();
        String data=GHtable.getModel().getValueAt(position, 0).toString();
        if(Controller.capNhatGH(data, vitri, kichthuoc, gia, tinhtrang)){
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            loadTable();
            tayText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txfGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGiaActionPerformed

    private void txfViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfViTriActionPerformed

    private void txfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTimKiemKeyReleased
        // TODO add your handling code here:
        Controller.timGianHang(GHtable, txfTimKiem.getText());
    }//GEN-LAST:event_txfTimKiemKeyReleased

    private void txfGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfGiaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGiaKeyReleased

    private void btnTrangChu() {
       new TrangChuView().setVisible(true);
       this.dispose();
    }
    private void loadTable() {
        Controller.getGianHang(GHtable);
    }
    public void tayText()
    {
        txfViTri.setText("");
        txfKichThuoc.setText("");
        txfGia.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GHtable;
    private javax.swing.JLabel GiajLabel;
    private javax.swing.JLabel KichThuocjLabel;
    private javax.swing.JLabel ViTrijLabel;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbKichThuoc;
    private javax.swing.JComboBox<String> cbViTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txfGia;
    private javax.swing.JTextField txfKichThuoc;
    private javax.swing.JTextField txfTimKiem;
    private javax.swing.JTextField txfTinhTrang;
    private javax.swing.JTextField txfViTri;
    // End of variables declaration//GEN-END:variables
}
