/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.khachHangController;
import Model.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author PC
 */
public class khachHangView extends javax.swing.JFrame {
    khachHangController Controller=new khachHangController();
    private static khachHangView instance=null;
    public static khachHangView getInstance(){
        if(instance==null)
            instance=new khachHangView();
        return instance;
    }
    /**
     * Creates new form nhanVienView
     */
    /** Creates new form khView */
    public khachHangView() {
        initComponents();
        loadTable();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbHo = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbNoiLamViec = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCMND = new javax.swing.JLabel();
        txfHo = new javax.swing.JTextField();
        txfTen = new javax.swing.JTextField();
        txfNoiLamViec = new javax.swing.JTextField();
        txfSDT = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txfCMND = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KHtable = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txfTimKiem = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Khách Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        lbHo.setBackground(new java.awt.Color(204, 204, 0));
        lbHo.setForeground(new java.awt.Color(204, 204, 0));
        lbHo.setText("Họ");

        lbTen.setBackground(new java.awt.Color(255, 255, 255));
        lbTen.setForeground(new java.awt.Color(204, 204, 0));
        lbTen.setText("Tên");

        lbNoiLamViec.setBackground(new java.awt.Color(255, 255, 255));
        lbNoiLamViec.setForeground(new java.awt.Color(204, 204, 0));
        lbNoiLamViec.setText("Nơi làm việc");

        lbSDT.setBackground(new java.awt.Color(255, 255, 255));
        lbSDT.setForeground(new java.awt.Color(204, 204, 0));
        lbSDT.setText("SDT");

        lbEmail.setBackground(new java.awt.Color(255, 255, 255));
        lbEmail.setForeground(new java.awt.Color(204, 204, 0));
        lbEmail.setText("Email");

        lbCMND.setBackground(new java.awt.Color(255, 255, 255));
        lbCMND.setForeground(new java.awt.Color(204, 204, 0));
        lbCMND.setText("CMND");

        txfHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfHoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHo)
                    .addComponent(lbTen)
                    .addComponent(lbNoiLamViec)
                    .addComponent(lbSDT)
                    .addComponent(lbEmail)
                    .addComponent(lbCMND))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfHo)
                    .addComponent(txfTen)
                    .addComponent(txfNoiLamViec)
                    .addComponent(txfSDT)
                    .addComponent(txfEmail)
                    .addComponent(txfCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHo)
                    .addComponent(txfHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTen)
                    .addComponent(txfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNoiLamViec)
                    .addComponent(txfNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSDT)
                    .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCMND)
                    .addComponent(txfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        KHtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ", "Tên", "Nơi làm việc", "SDT", "Email", "CMND"
            }
        ));
        KHtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KHtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KHtable);

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-find-user-male-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)
                        .addGap(31, 31, 31))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-left-20.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-plus-20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 255, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-minus-20.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-update-user-20.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addGap(209, 209, 209)
                        .addComponent(btnThoat)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnXoa))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCapNhat)
                        .addComponent(btnThoat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfHoActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String ho=txfHo.getText();
        String ten=txfTen.getText();
        String sdt=txfSDT.getText();
        String email=txfEmail.getText();
        String noilamviec=txfNoiLamViec.getText();
        String cmnd=txfCMND.getText();
        
        if(txfHo.getText().equals("")||txfTen.getText().equals("")||txfSDT.getText().equals("")||txfEmail.getText().equals("")||txfNoiLamViec.getText().equals("")||txfCMND.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
        else
            if(txfEmail.getText().matches("^[a-z][a-z0-9_\\.]{5,32}@[a-z0-9]{2,}(\\.[a-z0-9]{2,4}){1,2}$")==false ||txfSDT.getText().matches("(\\+84|0)\\d{9,10}")==false||txfCMND.getText().matches("\\d{9}")==false){
                JOptionPane.showMessageDialog(null, "vui lòng nhập đúng định dạng");
            }
            else
            {
                if(checkTrungCMND()==true){
                    JOptionPane.showMessageDialog(null, "CMND này đã tồn tại");
                    txfCMND.requestFocus();
                }
                else {
                    if(checkTrungEmail()==true){
                        JOptionPane.showMessageDialog(null, "Email này đã tồn tại");
                        txfEmail.requestFocus();
                    }
                    else{
                        if(checkTrungSDT()==true){
                            JOptionPane.showMessageDialog(null, "SDT này đã tồn tại");
                            txfSDT.requestFocus();
                        }
                        else{
                            if(Controller.themKH(ho, ten, sdt, email, noilamviec, cmnd)){
                                JOptionPane.showMessageDialog(null, "Thêm thành công");
                                loadTable();
                                tayText();
                            }
                           
                            else{
                                JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Thêm khách hàng thất bại !","Thông báo", JOptionPane.OK_OPTION);
                                }
                            }
                    }
                            
            }  
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex =KHtable.getSelectedRow();
        if(selectedIndex==0)
            JOptionPane.showMessageDialog(rootPane, 
                    "Danh sách khách hàng còn trống");
        else if(selectedIndex==-1)
            JOptionPane.showMessageDialog(rootPane, 
                    "Chọn khách hàng cần xóa");
        int data=KHtable.getSelectedRow();
        String makh=KHtable.getModel().getValueAt(data, 0).toString();
            int result=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không");
            if(result==0){
                if(Controller.xoaKH(makh)){
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    loadTable();
                    tayText();
                }
                else{
                    JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Xóa thất bại !","Thông báo", JOptionPane.OK_OPTION);
                     tayText();
                }
            
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        String ho=txfHo.getText();
        String ten=txfTen.getText();
        String sdt=txfSDT.getText();
        String email=txfEmail.getText();
        String noilamviec=txfNoiLamViec.getText();
        String cmnd=txfCMND.getText();
        int selectedIndex =KHtable.getSelectedRow();
        if(selectedIndex==-1)
            JOptionPane.showMessageDialog(rootPane, 
                    "Chọn khách hàng cần cập nhật");
        int position =KHtable.getSelectedRow();
        String data=KHtable.getModel().getValueAt(position, 0).toString();
        int result=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn cập nhật không");
        if(result==0){
            if(Controller.capNhatKH(data, ho, ten, sdt, email, noilamviec, cmnd)){
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                loadTable();
                tayText();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void KHtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KHtableMouseClicked
        // TODO add your handling code here:
        int i=KHtable.getSelectedRow();
        TableModel model= KHtable.getModel();
        txfHo.setText(model.getValueAt(i, 1).toString());
        txfTen.setText(model.getValueAt(i, 2).toString());
        txfSDT.setText(model.getValueAt(i, 3).toString());
        txfEmail.setText(model.getValueAt(i, 4).toString());
        txfNoiLamViec.setText(model.getValueAt(i, 5).toString());
        txfCMND.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_KHtableMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        if(evt.getSource().equals(btnThoat)){
            btnTrangChu();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Controller.timKhachHang(KHtable,txfTimKiem.getText());
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTimKiemKeyReleased
        // TODO add your handling code here:
        Controller.timKhachHang(KHtable, txfTimKiem.getText());
    }//GEN-LAST:event_txfTimKiemKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(khachHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(khachHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(khachHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(khachHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new khachHangView().setVisible(true);
//            }
//        });
//    }
    
    private void loadTable() {
        Controller.getKhachHang(KHtable);
    }
    public boolean checkTrungCMND() {
        try {
            Connection conn=DBConnection.getInstance().getConn();
            String query ="SELECT * FROM KHACHHANG WHERE CMND = ?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, txfCMND.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                return true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(khachHangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    public boolean checkTrungEmail(){
        try {
            Connection conn=DBConnection.getInstance().getConn();
            String query ="SELECT * FROM KHACHHANG WHERE Email = ?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, txfEmail.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                return true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(khachHangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    public boolean checkTrungSDT(){
        try {
            Connection conn=DBConnection.getInstance().getConn();
            String query ="SELECT * FROM KHACHHANG WHERE SDT = ?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, txfSDT.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                return true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(khachHangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    public void tayText()
    {
        txfHo.setText("");
        txfTen.setText("");
        txfSDT.setText("");
        txfEmail.setText("");
        txfNoiLamViec.setText("");
        txfCMND.setText("");
        
    }
    private void btnTrangChu() {
       new TrangChuView().setVisible(true);
       this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KHtable;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCMND;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbNoiLamViec;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTen;
    private javax.swing.JTextField txfCMND;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfHo;
    private javax.swing.JTextField txfNoiLamViec;
    private javax.swing.JTextField txfSDT;
    private javax.swing.JTextField txfTen;
    private javax.swing.JTextField txfTimKiem;
    // End of variables declaration//GEN-END:variables

}
