/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import Model.*;
import Controller.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author PC
 */
public class nhanVienView extends javax.swing.JFrame {
    
    nhanVienController Controller=new nhanVienController();
    private static nhanVienView instance=null;
    public static nhanVienView getInstance(){
        if(instance==null)
            instance=new nhanVienView();
        return instance;
    }
    /**
     * Creates new form nhanVienView
     */
    nhanVienView() {
        initComponents();
        loadTable();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NVtable = new javax.swing.JTable();
        txfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        HojLabel = new javax.swing.JLabel();
        TenjLabel = new javax.swing.JLabel();
        NgaySinhjLabel = new javax.swing.JLabel();
        SDTjLabel = new javax.swing.JLabel();
        EmailjLabel = new javax.swing.JLabel();
        DiaChijLabel = new javax.swing.JLabel();
        LuongjLabel = new javax.swing.JLabel();
        NgayVaoLamjLabel = new javax.swing.JLabel();
        MoTajLabel = new javax.swing.JLabel();
        txfHo = new javax.swing.JTextField();
        txfTen = new javax.swing.JTextField();
        txfNgaySinh = new javax.swing.JTextField();
        txfSDT = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txfDiaChi = new javax.swing.JTextField();
        txfLuong = new javax.swing.JTextField();
        txfNgayVaoLam = new javax.swing.JTextField();
        txfMoTa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        txfRole = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        NVtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ", "Tên", "Ngày sinh", "SDT", "Email", "Địa chỉ", "Lương", "Ngày vào làm", "Mô tả", "Username", "Password", "Role"
            }
        ));
        NVtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NVtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NVtable);

        txfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfTimKiemKeyReleased(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-find-user-male-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(204, 204, 0));

        HojLabel.setBackground(new java.awt.Color(255, 204, 144));
        HojLabel.setForeground(new java.awt.Color(204, 204, 0));
        HojLabel.setText("Họ");

        TenjLabel.setForeground(new java.awt.Color(204, 204, 0));
        TenjLabel.setText("Tên");

        NgaySinhjLabel.setForeground(new java.awt.Color(204, 204, 0));
        NgaySinhjLabel.setText("Ngày sinh");

        SDTjLabel.setForeground(new java.awt.Color(204, 204, 0));
        SDTjLabel.setText("SDT");

        EmailjLabel.setForeground(new java.awt.Color(204, 204, 0));
        EmailjLabel.setText("Email");

        DiaChijLabel.setForeground(new java.awt.Color(204, 204, 0));
        DiaChijLabel.setText("Địa Chỉ");

        LuongjLabel.setForeground(new java.awt.Color(204, 204, 0));
        LuongjLabel.setText("Lương");

        NgayVaoLamjLabel.setForeground(new java.awt.Color(204, 204, 0));
        NgayVaoLamjLabel.setText("Ngày vào làm");

        MoTajLabel.setBackground(new java.awt.Color(204, 204, 0));
        MoTajLabel.setForeground(new java.awt.Color(204, 204, 0));
        MoTajLabel.setText("Mô tả");

        txfHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfHoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Username ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Password");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Role");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SDTjLabel)
                    .addComponent(EmailjLabel)
                    .addComponent(NgaySinhjLabel)
                    .addComponent(DiaChijLabel)
                    .addComponent(LuongjLabel)
                    .addComponent(NgayVaoLamjLabel)
                    .addComponent(MoTajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TenjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfHo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DiaChijLabel, EmailjLabel, HojLabel, LuongjLabel, MoTajLabel, NgaySinhjLabel, NgayVaoLamjLabel, SDTjLabel, TenjLabel, jLabel2, jLabel3, jLabel4});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txfDiaChi, txfEmail, txfHo, txfLuong, txfMoTa, txfNgaySinh, txfNgayVaoLam, txfPassword, txfRole, txfSDT, txfTen, txfUsername});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HojLabel)
                    .addComponent(txfHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenjLabel)
                    .addComponent(txfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NgaySinhjLabel)
                    .addComponent(txfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDTjLabel)
                    .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailjLabel)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaChijLabel)
                    .addComponent(txfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LuongjLabel)
                    .addComponent(txfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NgayVaoLamjLabel)
                    .addComponent(txfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoTajLabel)
                    .addComponent(txfMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DiaChijLabel, EmailjLabel, HojLabel, LuongjLabel, MoTajLabel, NgaySinhjLabel, NgayVaoLamjLabel, SDTjLabel, TenjLabel, jLabel2, jLabel3, jLabel4});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txfDiaChi, txfEmail, txfHo, txfLuong, txfMoTa, txfNgaySinh, txfNgayVaoLam, txfPassword, txfRole, txfSDT, txfTen, txfUsername});

        btnXoa.setBackground(new java.awt.Color(204, 255, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-minus-20.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 255, 204));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-update-user-20.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-left-20.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-plus-20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(42, 42, 42)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addGap(56, 56, 56)
                        .addComponent(btnThoat))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnCapNhat)
                            .addComponent(btnThoat)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhat, btnThem, btnThoat, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //if(la admin)
        String ho=txfHo.getText();
        String ten=txfTen.getText();
        String ngaysinh=txfNgaySinh.getText();
        String sdt=txfSDT.getText();
        String email=txfEmail.getText();
        String diachi=txfDiaChi.getText();
        String luong=txfLuong.getText();
        String ngayvaolam=txfNgayVaoLam.getText();
        String mota=txfMoTa.getText();
        String username=txfUsername.getText();
        String password=txfPassword.getText();
        String role=txfRole.getText();
        if(txfHo.getText().equals("")||txfTen.getText().equals("")||txfNgaySinh.getText().equals("")||txfSDT.getText().equals("")||
            txfEmail.getText().equals("")||txfDiaChi.getText().equals("")||txfLuong.getText().equals("")||
            txfNgayVaoLam.getText().equals("")||txfUsername.getText().equals("")||txfPassword.getText().equals("")||
            txfRole.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        }
        else
        if(txfEmail.getText().matches("^[a-z][a-z0-9_\\.]{5,32}@[a-z0-9]{2,}(\\.[a-z0-9]{2,4}){1,2}$")==false
            ||txfSDT.getText().matches("(\\+84|0)\\d{9,10}")==false){
            JOptionPane.showMessageDialog(null, "vui lòng nhập đúng định dạng");
        }
        else
        {
            if(checkTrungEmail()==true){
                JOptionPane.showMessageDialog(null, "Email này đã tồn tại");
                txfEmail.requestFocus();
            }
            else{
                if(checkTrungSDT()==true){
                    JOptionPane.showMessageDialog(null, "SDT này đã tồn tại");
                    txfSDT.requestFocus();
                }
                else{
                    if(Controller.themNV(ho, ten, ngaysinh, sdt, email, diachi, luong, ngayvaolam, mota, username, password, role)){
                        JOptionPane.showMessageDialog(null, "Thêm thành công");
                        loadTable();
                        tayText();
                    }
                    else{
                        JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Thêm nhân viên thất bại !","Thông báo", JOptionPane.OK_OPTION);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        if(evt.getSource().equals(btnThoat)){
            btnTrangChu();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        String ho=txfHo.getText();
        String ten=txfTen.getText();
        String ngaysinh=txfNgaySinh.getText();
        String sdt=txfSDT.getText();
        String email=txfEmail.getText();
        String diachi=txfDiaChi.getText();
        String luong=txfLuong.getText();
        String ngayvaolam=txfNgayVaoLam.getText();
        String mota=txfMoTa.getText();
        String username=txfUsername.getText();
        String password=txfPassword.getText();
        String role=txfRole.getText();
        int position =NVtable.getSelectedRow();
        String data=NVtable.getModel().getValueAt(position, 0).toString();
        if(Controller.capNhatNV(data, ho, ten, ngaysinh, sdt, email, diachi, luong, ngayvaolam, mota, username, password, role)){
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            loadTable();
            tayText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex =NVtable.getSelectedRow();
        if(selectedIndex==-1)
        JOptionPane.showMessageDialog(rootPane,
            "Chọn nhân viên cần xóa");
        int data=NVtable.getSelectedRow();
        String manv=NVtable.getModel().getValueAt(data, 0).toString();
        int result=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không");
        if(result==0){
            if(Controller.xoaNV(manv)){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                loadTable();
                tayText();
            }
            else{
                JOptionPane.showConfirmDialog(khachHangView.getInstance(), "Xóa thất bại !","Thông báo", JOptionPane.OK_OPTION);
                tayText();
            }

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txfHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfHoActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Controller.timNhanVien(NVtable, txfTimKiem.getText());
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void NVtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVtableMouseClicked
        int i=NVtable.getSelectedRow();
        TableModel model= NVtable.getModel();
        txfHo.setText(model.getValueAt(i, 1).toString());
        txfTen.setText(model.getValueAt(i, 2).toString());
        txfNgaySinh.setText(model.getValueAt(i, 3).toString());
        txfSDT.setText(model.getValueAt(i, 4).toString());
        txfEmail.setText(model.getValueAt(i, 5).toString());
        txfDiaChi.setText(model.getValueAt(i, 6).toString());
        txfLuong.setText(model.getValueAt(i, 7).toString());
        txfNgayVaoLam.setText(model.getValueAt(i, 8).toString());
        txfMoTa.setText(model.getValueAt(i, 9).toString());
        txfUsername.setText(model.getValueAt(i, 10).toString());
        txfPassword.setText(model.getValueAt(i, 11).toString());
        txfRole.setText(model.getValueAt(i, 12).toString());
    }//GEN-LAST:event_NVtableMouseClicked

    private void txfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfTimKiemKeyReleased
        // TODO add your handling code here:
        Controller.timNhanVien(NVtable, txfTimKiem.getText());
    }//GEN-LAST:event_txfTimKiemKeyReleased
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(nhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(nhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(nhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(nhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new nhanVienView().setVisible(true);
//            }
//        });
//    }
    private void btnTrangChu() {
       new TrangChuView().setVisible(true);
       this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiaChijLabel;
    private javax.swing.JLabel EmailjLabel;
    private javax.swing.JLabel HojLabel;
    private javax.swing.JLabel LuongjLabel;
    private javax.swing.JLabel MoTajLabel;
    private javax.swing.JTable NVtable;
    private javax.swing.JLabel NgaySinhjLabel;
    private javax.swing.JLabel NgayVaoLamjLabel;
    private javax.swing.JLabel SDTjLabel;
    private javax.swing.JLabel TenjLabel;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txfDiaChi;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfHo;
    private javax.swing.JTextField txfLuong;
    private javax.swing.JTextField txfMoTa;
    private javax.swing.JTextField txfNgaySinh;
    private javax.swing.JTextField txfNgayVaoLam;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfRole;
    private javax.swing.JTextField txfSDT;
    private javax.swing.JTextField txfTen;
    private javax.swing.JTextField txfTimKiem;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
    
    private void loadTable() {
        Controller.getNhanVien(NVtable);
    }
    public void tayText(){
        txfHo.setText("");
        txfTen.setText("");
        txfDiaChi.setText("");
        txfEmail.setText("");
        txfLuong.setText("");
        txfMoTa.setText("");
        txfNgaySinh.setText("");
        txfNgayVaoLam.setText("");
        txfSDT.setText("");
        txfUsername.setText("");
        txfPassword.setText("");
        txfRole.setText("");
        
    }
    public boolean checkTrungEmail(){
        try {
            Connection conn=DBConnection.getInstance().getConn();
            String query ="SELECT * FROM NHANSU WHERE Email = ?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, txfEmail.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                return true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(khachHangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    public boolean checkTrungSDT(){
        try {
            Connection conn=DBConnection.getInstance().getConn();
            String query ="SELECT * FROM NHANSU WHERE SDT = ?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, txfSDT.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                return true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(khachHangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
}
